In [1]:
#Standardizing only the Numerical Variables(Creating a custom Scaler)

#Import libraries
import pandas as pd
import numpy as np

In [2]:
#Load the data
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Month Value,Day of the Week,Absenteeism Time in Hours
0,0,0,0,1,289,36,33,239.554,30,0,2,1,7,1,4
1,0,0,0,0,118,13,50,239.554,31,0,1,0,7,1,0
2,0,0,0,1,179,51,38,239.554,31,0,0,0,7,2,2
3,1,0,0,0,279,5,39,239.554,24,0,2,0,7,3,4
4,0,0,0,1,289,36,33,239.554,30,0,2,1,7,3,2
5,0,0,0,1,179,51,38,239.554,31,0,0,0,7,4,2
6,0,0,0,1,361,52,28,239.554,27,0,1,4,7,4,8
7,0,0,0,1,260,50,36,239.554,23,0,4,0,7,4,4
8,0,0,1,0,155,12,34,239.554,25,0,2,0,7,0,40
9,0,0,0,1,235,11,37,239.554,29,1,1,1,7,0,8
10,1,0,0,0,260,50,36,239.554,23,0,4,0,7,0,8
11,1,0,0,0,260,50,36,239.554,23,0,4,0,7,1,8
12,1,0,0,0,260,50,36,239.554,23,0,4,0,7,2,8
13,1,0,0,0,179,51,38,239.554,31,0,0,0,7,2,1
14,0,0,0,1,179,51,38,239.554,31,0,0,0,7,2,4
15,1,0,0,0,246,25,41,239.554,23,0,0,0,7,4,8
16,0,0,0,1,179,51,38,239.554,31,0,0,0,7,4,2
17,0,0,1,0,179,51,38,239.554,31,0,0,0,7,0,8
18,1,0,0,0,189,29,33,239.554,25,0,2,2,7,3,8
19,0,0,0,1,248,25,47,205.917,32,0,2,1,8,2,2
20,1,0,0,0,330,16,28,205.917,25,1,0,0,8,2,8
21,1,0,0,0,179,51,38,205.917,31,0,0,0,8,0,1
22,1,0,0,0,361,52,28,205.917,27,0,1,4,8,0,40
23,0,0,0,1,260,50,36,205.917,23,0,4,0,8,4,4
24,0,0,1,0,289,36,33,205.917,30,0,2,1,8,0,8
25,0,0,0,1,361,52,28,205.917,27,0,1,4,8,0,7
26,0,0,0,1,289,36,33,205.917,30,0,2,1,8,1,1
27,0,0,0,1,157,27,29,205.917,22,0,0,0,8,2,4
28,0,0,1,0,289,36,33,205.917,30,0,2,1,8,2,8
29,0,0,0,1,179,51,38,205.917,31,0,0,0,8,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,155,12,34,246.288,25,0,2,0,4,1,4
671,0,0,1,0,225,26,28,246.288,24,0,1,2,4,3,8
672,1,0,0,0,118,13,50,246.288,31,0,1,0,4,3,2
673,0,0,0,1,179,26,30,246.288,19,1,0,0,4,4,2
674,0,0,0,1,235,11,37,237.656,29,1,1,1,5,0,8
675,0,0,1,0,225,15,41,237.656,28,1,2,2,5,2,3
676,0,0,0,1,235,16,32,237.656,25,1,0,0,5,2,2
677,1,0,0,0,118,10,37,237.656,28,0,0,0,5,2,3
678,0,0,0,1,235,20,43,237.656,38,0,1,0,5,2,8
679,1,0,0,0,179,26,30,237.656,19,1,0,0,5,3,1
680,0,0,0,1,291,31,40,237.656,25,0,1,1,5,3,2
681,1,0,0,0,225,15,41,237.656,28,1,2,2,5,3,8
682,0,0,1,0,300,26,43,237.656,25,0,2,1,5,4,64
683,0,0,0,1,225,15,41,237.656,28,1,2,2,5,4,8
684,0,0,0,1,179,26,30,237.656,19,1,0,0,5,4,2
685,0,0,0,1,118,13,50,237.656,31,0,1,0,5,0,2
686,1,0,0,0,118,13,50,237.656,31,0,1,0,5,1,3
687,0,0,0,1,118,10,37,237.656,28,0,0,0,5,1,1
688,0,0,0,0,118,13,50,237.656,31,0,1,0,5,1,0
689,0,0,0,1,179,26,30,237.656,19,1,0,0,5,2,2
690,0,0,0,0,378,49,36,237.656,21,0,2,4,5,2,0
691,0,1,0,0,179,22,40,237.656,22,1,2,0,5,4,1
692,1,0,0,0,155,12,34,237.656,25,0,2,0,5,0,48
693,1,0,0,0,235,16,32,237.656,25,1,0,0,5,0,8
694,0,0,0,1,291,31,40,237.656,25,0,1,1,5,2,8
695,1,0,0,0,179,22,40,237.656,22,1,2,0,5,2,8
696,1,0,0,0,225,26,28,237.656,24,0,1,2,5,2,3
697,1,0,0,0,330,16,28,237.656,25,1,0,0,5,3,8
698,0,0,0,1,235,16,32,237.656,25,1,0,0,5,3,2
699,0,0,0,1,291,31,40,237.656,25,0,1,1,5,3,2

In [4]:
#Targets
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head(10)

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Month Value,Day of the Week,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,289,36,33,239.554,30,0,2,1,7,1,4,1
1,0,0,0,0,118,13,50,239.554,31,0,1,0,7,1,0,0
2,0,0,0,1,179,51,38,239.554,31,0,0,0,7,2,2,0
3,1,0,0,0,279,5,39,239.554,24,0,2,0,7,3,4,1
4,0,0,0,1,289,36,33,239.554,30,0,2,1,7,3,2,0
5,0,0,0,1,179,51,38,239.554,31,0,0,0,7,4,2,0
6,0,0,0,1,361,52,28,239.554,27,0,1,4,7,4,8,1
7,0,0,0,1,260,50,36,239.554,23,0,4,0,7,4,4,1
8,0,0,1,0,155,12,34,239.554,25,0,2,0,7,0,40,1
9,0,0,0,1,235,11,37,239.554,29,1,1,1,7,0,8,1

In [8]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

In [10]:
data_with_targets is data_preprocessed

False

In [11]:
data_with_targets.head()

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Month Value,Day of the Week,Excessive Absenteeism
0,0,0,0,1,289,36,33,239.554,30,0,2,1,7,1,1
1,0,0,0,0,118,13,50,239.554,31,0,1,0,7,1,0
2,0,0,0,1,179,51,38,239.554,31,0,0,0,7,2,0
3,1,0,0,0,279,5,39,239.554,24,0,2,0,7,3,1
4,0,0,0,1,289,36,33,239.554,30,0,2,1,7,3,0

In [12]:
#Selecting the inputs for the logistic regression
data_with_targets.shape

(700, 15)

In [13]:
unscaled_inputs = data_with_targets.iloc[:, :-1]
unscaled_inputs

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Month Value,Day of the Week
0,0,0,0,1,289,36,33,239.554,30,0,2,1,7,1
1,0,0,0,0,118,13,50,239.554,31,0,1,0,7,1
2,0,0,0,1,179,51,38,239.554,31,0,0,0,7,2
3,1,0,0,0,279,5,39,239.554,24,0,2,0,7,3
4,0,0,0,1,289,36,33,239.554,30,0,2,1,7,3
5,0,0,0,1,179,51,38,239.554,31,0,0,0,7,4
6,0,0,0,1,361,52,28,239.554,27,0,1,4,7,4
7,0,0,0,1,260,50,36,239.554,23,0,4,0,7,4
8,0,0,1,0,155,12,34,239.554,25,0,2,0,7,0
9,0,0,0,1,235,11,37,239.554,29,1,1,1,7,0
10,1,0,0,0,260,50,36,239.554,23,0,4,0,7,0
11,1,0,0,0,260,50,36,239.554,23,0,4,0,7,1
12,1,0,0,0,260,50,36,239.554,23,0,4,0,7,2
13,1,0,0,0,179,51,38,239.554,31,0,0,0,7,2
14,0,0,0,1,179,51,38,239.554,31,0,0,0,7,2
15,1,0,0,0,246,25,41,239.554,23,0,0,0,7,4
16,0,0,0,1,179,51,38,239.554,31,0,0,0,7,4
17,0,0,1,0,179,51,38,239.554,31,0,0,0,7,0
18,1,0,0,0,189,29,33,239.554,25,0,2,2,7,3
19,0,0,0,1,248,25,47,205.917,32,0,2,1,8,2
20,1,0,0,0,330,16,28,205.917,25,1,0,0,8,2
21,1,0,0,0,179,51,38,205.917,31,0,0,0,8,0
22,1,0,0,0,361,52,28,205.917,27,0,1,4,8,0
23,0,0,0,1,260,50,36,205.917,23,0,4,0,8,4
24,0,0,1,0,289,36,33,205.917,30,0,2,1,8,0
25,0,0,0,1,361,52,28,205.917,27,0,1,4,8,0
26,0,0,0,1,289,36,33,205.917,30,0,2,1,8,1
27,0,0,0,1,157,27,29,205.917,22,0,0,0,8,2
28,0,0,1,0,289,36,33,205.917,30,0,2,1,8,2
29,0,0,0,1,179,51,38,205.917,31,0,0,0,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,155,12,34,246.288,25,0,2,0,4,1
671,0,0,1,0,225,26,28,246.288,24,0,1,2,4,3
672,1,0,0,0,118,13,50,246.288,31,0,1,0,4,3
673,0,0,0,1,179,26,30,246.288,19,1,0,0,4,4
674,0,0,0,1,235,11,37,237.656,29,1,1,1,5,0
675,0,0,1,0,225,15,41,237.656,28,1,2,2,5,2
676,0,0,0,1,235,16,32,237.656,25,1,0,0,5,2
677,1,0,0,0,118,10,37,237.656,28,0,0,0,5,2
678,0,0,0,1,235,20,43,237.656,38,0,1,0,5,2
679,1,0,0,0,179,26,30,237.656,19,1,0,0,5,3
680,0,0,0,1,291,31,40,237.656,25,0,1,1,5,3
681,1,0,0,0,225,15,41,237.656,28,1,2,2,5,3
682,0,0,1,0,300,26,43,237.656,25,0,2,1,5,4
683,0,0,0,1,225,15,41,237.656,28,1,2,2,5,4
684,0,0,0,1,179,26,30,237.656,19,1,0,0,5,4
685,0,0,0,1,118,13,50,237.656,31,0,1,0,5,0
686,1,0,0,0,118,13,50,237.656,31,0,1,0,5,1
687,0,0,0,1,118,10,37,237.656,28,0,0,0,5,1
688,0,0,0,0,118,13,50,237.656,31,0,1,0,5,1
689,0,0,0,1,179,26,30,237.656,19,1,0,0,5,2
690,0,0,0,0,378,49,36,237.656,21,0,2,4,5,2
691,0,1,0,0,179,22,40,237.656,22,1,2,0,5,4
692,1,0,0,0,155,12,34,237.656,25,0,2,0,5,0
693,1,0,0,0,235,16,32,237.656,25,1,0,0,5,0
694,0,0,0,1,291,31,40,237.656,25,0,1,1,5,2
695,1,0,0,0,179,22,40,237.656,22,1,2,0,5,2
696,1,0,0,0,225,26,28,237.656,24,0,1,2,5,2
697,1,0,0,0,330,16,28,237.656,25,1,0,0,5,3
698,0,0,0,1,235,16,32,237.656,25,1,0,0,5,3
699,0,0,0,1,291,31,40,237.656,25,0,1,1,5,3

In [14]:
#Standardizing the data
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [16]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week'], dtype=object)

In [17]:
columns_to_scale = ['Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index','Children', 
                    'Pets', 'Month Value', 'Day of the Week']

In [18]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [19]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Transportation Expense', 'Distance to Work', 'Age',
                      'Daily Work Load Average', 'Body Mass Index', 'Children',
                      'Pets', 'Month Value', 'Day of the Week'],
             copy=None, with_mean=None, with_std=None)

In [20]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [21]:
scaled_inputs

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Month Value,Day of the Week
0,0,0,0,1,1.005844,0.412816,-0.536062,-0.806331,0.767431,0,0.880469,0.268487,0.182726,-0.683704
1,0,0,0,0,-1.574681,-1.141882,2.130803,-0.806331,1.002633,0,-0.019280,-0.589690,0.182726,-0.683704
2,0,0,0,1,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690,0.182726,-0.007725
3,1,0,0,0,0.854936,-1.682647,0.405184,-0.806331,-0.643782,0,0.880469,-0.589690,0.182726,0.668253
4,0,0,0,1,1.005844,0.412816,-0.536062,-0.806331,0.767431,0,0.880469,0.268487,0.182726,0.668253
5,0,0,0,1,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690,0.182726,1.344231
6,0,0,0,1,2.092381,1.494345,-1.320435,-0.806331,0.061825,0,-0.019280,2.843016,0.182726,1.344231
7,0,0,0,1,0.568211,1.359154,-0.065439,-0.806331,-0.878984,0,2.679969,-0.589690,0.182726,1.344231
8,0,0,1,0,-1.016322,-1.209478,-0.379188,-0.806331,-0.408580,0,0.880469,-0.589690,0.182726,-1.359682
9,0,0,0,1,0.190942,-1.277074,0.091435,-0.806331,0.532229,1,-0.019280,0.268487,0.182726,-1.359682
10,1,0,0,0,0.568211,1.359154,-0.065439,-0.806331,-0.878984,0,2.679969,-0.589690,0.182726,-1.359682
11,1,0,0,0,0.568211,1.359154,-0.065439,-0.806331,-0.878984,0,2.679969,-0.589690,0.182726,-0.683704
12,1,0,0,0,0.568211,1.359154,-0.065439,-0.806331,-0.878984,0,2.679969,-0.589690,0.182726,-0.007725
13,1,0,0,0,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690,0.182726,-0.007725
14,0,0,0,1,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690,0.182726,-0.007725
15,1,0,0,0,0.356940,-0.330735,0.718933,-0.806331,-0.878984,0,-0.919030,-0.589690,0.182726,1.344231
16,0,0,0,1,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690,0.182726,1.344231
17,0,0,1,0,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690,0.182726,-1.359682
18,1,0,0,0,-0.503235,-0.060353,-0.536062,-0.806331,-0.408580,0,0.880469,1.126663,0.182726,0.668253
19,0,0,0,1,0.387122,-0.330735,1.660180,-1.647399,1.237836,0,0.880469,0.268487,0.468236,-0.007725
20,1,0,0,0,1.624567,-0.939096,-1.320435,-1.647399,-0.408580,1,-0.919030,-0.589690,0.468236,-0.007725
21,1,0,0,0,-0.654143,1.426749,0.248310,-1.647399,1.002633,0,-0.919030,-0.589690,0.468236,-1.359682
22,1,0,0,0,2.092381,1.494345,-1.320435,-1.647399,0.061825,0,-0.019280,2.843016,0.468236,-1.359682
23,0,0,0,1,0.568211,1.359154,-0.065439,-1.647399,-0.878984,0,2.679969,-0.589690,0.468236,1.344231
24,0,0,1,0,1.005844,0.412816,-0.536062,-1.647399,0.767431,0,0.880469,0.268487,0.468236,-1.359682
25,0,0,0,1,2.092381,1.494345,-1.320435,-1.647399,0.061825,0,-0.019280,2.843016,0.468236,-1.359682
26,0,0,0,1,1.005844,0.412816,-0.536062,-1.647399,0.767431,0,0.880469,0.268487,0.468236,-0.683704
27,0,0,0,1,-0.986140,-0.195544,-1.163560,-1.647399,-1.114186,0,-0.919030,-0.589690,0.468236,-0.007725
28,0,0,1,0,1.005844,0.412816,-0.536062,-1.647399,0.767431,0,0.880469,0.268487,0.468236,-0.007725
29,0,0,0,1,-0.654143,1.426749,0.248310,-1.647399,1.002633,0,-0.919030,-0.589690,0.468236,1.344231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,-1.016322,-1.209478,-0.379188,-0.637953,-0.408580,0,0.880469,-0.589690,-0.673803,-0.683704
671,0,0,1,0,0.040034,-0.263140,-1.320435,-0.637953,-0.643782,0,-0.019280,1.126663,-0.673803,0.668253
672,1,0,0,0,-1.574681,-1.141882,2.130803,-0.637953,1.002633,0,-0.019280,-0.589690,-0.673803,0.668253
673,0,0,0,1,-0.654143,-0.263140,-1.006686,-0.637953,-1.819793,1,-0.919030,-0.589690,-0.673803,1.344231
674,0,0,0,1,0.190942,-1.277074,0.091435,-0.853789,0.532229,1,-0.019280,0.268487,-0.388293,-1.359682
675,0,0,1,0,0.040034,-1.006691,0.718933,-0.853789,0.297027,1,0.880469,1.126663,-0.388293,-0.007725
676,0,0,0,1,0.190942,-0.939096,-0.692937,-0.853789,-0.408580,1,-0.919030,-0.589690,-0.388293,-0.007725
677,1,0,0,0,-1.574681,-1.344669,0.091435,-0.853789,0.297027,0,-0.919030,-0.589690,-0.388293,-0.007725
678,0,0,0,1,0.190942,-0.668713,1.032682,-0.853789,2.649049,0,-0.019280,-0.589690,-0.388293,-0.007725
679,1,0,0,0,-0.654143,-0.263140,-1.006686,-0.853789,-1.819793,1,-0.919030,-0.589690,-0.388293,0.668253
680,0,0,0,1,1.036026,0.074838,0.562059,-0.853789,-0.408580,0,-0.019280,0.268487,-0.388293,0.668253
681,1,0,0,0,0.040034,-1.006691,0.718933,-0.853789,0.297027,1,0.880469,1.126663,-0.388293,0.668253
682,0,0,1,0,1.171843,-0.263140,1.032682,-0.853789,-0.408580,0,0.880469,0.268487,-0.388293,1.344231
683,0,0,0,1,0.040034,-1.006691,0.718933,-0.853789,0.297027,1,0.880469,1.126663,-0.388293,1.344231
684,0,0,0,1,-0.654143,-0.263140,-1.006686,-0.853789,-1.819793,1,-0.919030,-0.589690,-0.388293,1.344231
685,0,0,0,1,-1.574681,-1.141882,2.130803,-0.853789,1.002633,0,-0.019280,-0.589690,-0.388293,-1.359682
686,1,0,0,0,-1.574681,-1.141882,2.130803,-0.853789,1.002633,0,-0.019280,-0.589690,-0.388293,-0.683704
687,0,0,0,1,-1.574681,-1.344669,0.091435,-0.853789,0.297027,0,-0.919030,-0.589690,-0.388293,-0.683704
688,0,0,0,0,-1.574681,-1.141882,2.130803,-0.853789,1.002633,0,-0.019280,-0.589690,-0.388293,-0.683704
689,0,0,0,1,-0.654143,-0.263140,-1.006686,-0.853789,-1.819793,1,-0.919030,-0.589690,-0.388293,-0.007725
690,0,0,0,0,2.348925,1.291558,-0.065439,-0.853789,-1.349389,0,0.880469,2.843016,-0.388293,-0.007725
691,0,1,0,0,-0.654143,-0.533522,0.562059,-0.853789,-1.114186,1,0.880469,-0.589690,-0.388293,1.344231
692,1,0,0,0,-1.016322,-1.209478,-0.379188,-0.853789,-0.408580,0,0.880469,-0.589690,-0.388293,-1.359682
693,1,0,0,0,0.190942,-0.939096,-0.692937,-0.853789,-0.408580,1,-0.919030,-0.589690,-0.388293,-1.359682
694,0,0,0,1,1.036026,0.074838,0.562059,-0.853789,-0.408580,0,-0.019280,0.268487,-0.388293,-0.007725
695,1,0,0,0,-0.654143,-0.533522,0.562059,-0.853789,-1.114186,1,0.880469,-0.589690,-0.388293,-0.007725
696,1,0,0,0,0.040034,-0.263140,-1.320435,-0.853789,-0.643782,0,-0.019280,1.126663,-0.388293,-0.007725
697,1,0,0,0,1.624567,-0.939096,-1.320435,-0.853789,-0.408580,1,-0.919030,-0.589690,-0.388293,0.668253
698,0,0,0,1,0.190942,-0.939096,-0.692937,-0.853789,-0.408580,1,-0.919030,-0.589690,-0.388293,0.668253
699,0,0,0,1,1.036026,0.074838,0.562059,-0.853789,-0.408580,0,-0.019280,0.268487,-0.388293,0.668253

In [22]:
#Splitting the date for training and testing
from sklearn.model_selection import train_test_split

In [23]:
train_test_split(scaled_inputs, targets)

[     reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
 686         1         0         0         0               -1.574681
 549         0         0         0         0                1.005844
 391         0         0         1         0                0.356940
 350         0         0         0         1                0.190942
 599         0         0         0         1                0.040034
 555         1         0         0         0               -0.654143
 307         0         0         0         1                1.036026
 327         1         0         0         0               -1.574681
 364         1         0         0         0                1.036026
 197         0         0         1         0                0.568211
 372         0         0         0         1                1.005844
 443         0         0         0         1               -1.574681
 146         0         0         0         1                0.040034
 398         0         0         0         1               -0.654143
 379         0         0         0         1               -0.654143
 400         0         0         0         0                2.213108
 371         1         0         0         0                0.040034
 394         0         0         0         1               -0.654143
 465         0         0         0         1               -1.574681
 665         0         0         0         1                0.190942
 696         1         0         0         0                0.040034
 643         0         0         0         1               -0.654143
 618         0         0         0         1               -0.654143
 635         1         0         0         0                0.387122
 417         0         0         0         1                1.624567
 514         0         0         0         1                1.036026
 249         0         0         1         0                1.005844
 647         0         0         0         1               -1.574681
 157         0         0         1         0               -0.986140
 457         0         0         0         1                0.356940
 ..        ...       ...       ...       ...                     ...
 324         0         0         0         1                0.190942
 657         0         0         1         0                0.387122
 525         1         0         0         0                2.213108
 429         0         0         0         1               -0.654143
 522         0         0         0         1                1.036026
 456         0         0         1         0               -0.654143
 285         0         0         0         0                0.190942
 164         1         0         0         0               -0.654143
 11          1         0         0         0                0.568211
 268         1         0         0         0                2.092381
 181         0         0         0         1                0.040034
 631         0         0         0         1               -0.654143
 471         1         0         0         0                0.040034
 137         0         0         0         1               -0.578689
 14          0         0         0         1               -0.654143
 626         0         0         0         1                0.040034
 414         0         0         0         1                1.624567
 235         0         0         0         1                0.040034
 560         0         0         0         1                0.040034
 186         0         0         0         1               -1.016322
 574         1         0         0         0               -0.654143
 550         1         0         0         0                0.387122
 124         0         0         0         1               -1.574681
 676         0         0         0         1                0.190942
 632         0         0         0         1               -0.654143
 58          0         0         0         0                2.213108
 90          0         0         0         1                0.040034
 538         1         0         0         0                0.190942
 418         0         0         0         1               -0.654143
 446         0         0         0         0               -0.654143

      Distance to Work       Age  Daily Work Load Average  Body Mass Index  \
 686         -1.141882  2.130803                -0.853789         1.002633
 549          0.412816 -0.536062                -0.082083         0.767431
 391         -0.330735  0.718933                -0.685486        -0.878984
 350         -1.277074  0.091435                -0.879469         0.532229
 599         -0.263140 -1.320435                -0.188851        -0.643782
 555          1.426749  0.248310                 0.218718         1.002633
 307          0.074838  0.562059                -0.169648        -0.408580
 327         -1.344669  0.091435                 0.305783         0.297027
 364          0.074838  0.562059                 1.456728        -0.408580
 197          1.359154 -0.065439                 1.366488        -0.878984
 372          0.412816 -0.536062                -0.499679         0.767431
 443         -1.344669  0.091435                -0.446195         0.297027
 146         -0.263140 -1.320435                 0.769711        -0.643782
 398          1.426749  0.248310                -0.685486         1.002633
 379          1.426749  0.248310                -0.499679         1.002633
 400         -0.871500 -0.849811                -0.685486        -0.408580
 371         -0.263140 -1.320435                -0.499679        -0.643782
 394          1.426749  0.248310                -0.685486         1.002633
 465         -1.344669  0.091435                -1.037971         0.297027
 665         -1.277074  0.091435                -0.637953         0.532229
 696         -0.263140 -1.320435                -0.853789        -0.643782
 643          1.426749  0.248310                -1.240355         1.002633
 618          1.426749  0.248310                -1.240355         1.002633
 635         -0.330735  1.660180                -1.240355         1.237836
 417         -0.939096 -1.320435                -0.809957        -0.408580
 514          0.074838  0.562059                 0.326336        -0.408580
 249          0.412816 -0.536062                 0.087771         0.767431
 647         -1.006691  1.503305                -1.240355        -0.408580
 157         -0.195544 -1.163560                 1.786584        -1.114186
 457         -0.330735  0.718933                -0.446195        -0.878984
 ..                ...       ...                      ...              ...
 324         -0.668713  1.032682                 0.305783         2.649049
 657         -0.330735  1.660180                -0.637953         1.237836
 525         -0.871500 -0.849811                 0.326336        -0.408580
 429          1.426749  0.248310                -0.643304         1.002633
 522          0.074838  0.562059                 0.326336        -0.408580
 456         -0.263140 -1.006686                -0.446195        -1.819793
 285         -0.668713  1.032682                 0.560476         2.649049
 164         -0.533522  0.562059                 1.786584        -1.114186
 11           1.359154 -0.065439                -0.806331        -0.878984
 268          1.494345 -1.320435                -0.154696         0.061825
 181         -0.263140 -1.320435                 1.786584        -0.643782
 631          1.426749  0.248310                -1.240355         1.002633
 471         -0.263140 -1.320435                -1.037971        -0.643782
 137          0.818389 -1.477309                 0.769711        -1.349389
 14           1.426749  0.248310                -0.806331         1.002633
 626         -0.263140 -1.320435                -1.240355        -0.643782
 414         -0.939096 -1.320435                -0.809957        -0.408580
 235         -0.263140 -1.320435                 2.644155        -0.643782
 560         -0.263140 -1.320435                 0.218718        -0.643782
 186         -1.209478 -0.379188                 1.366488        -0.408580
 574         -0.263140 -1.006686                 1.043433        -1.819793
 550         -0.330735  1.660180                -0.082083         1.237836
 124         -1.344669  0.091435                 0.919937         0.297027
 676         -0.939096 -0.692937                -0.853789        -0.408580
 632          1.426749  0.248310                -1.240355         1.002633
 58          -0.871500 -0.849811                -0.758273        -0.408580
 90          -0.263140 -1.320435                 0.863727        -0.643782
 538         -0.939096 -0.692937                -0.082083        -0.408580
 418          1.426749  0.248310                -0.809957         1.002633
 446          1.426749  0.248310                -0.446195         1.002633

      Education  Children      Pets  Month Value  Day of the Week
 686          0 -0.019280 -0.589690    -0.388293        -0.683704
 549          0  0.880469  0.268487     1.324766        -0.007725
 391          0 -0.919030 -0.589690    -0.959313        -0.007725
 350          1 -0.019280  0.268487     1.610276         0.668253
 599          0 -0.019280  1.126663    -1.244823         0.668253
 555          0 -0.919030 -0.589690     1.610276        -0.683704
 307          0 -0.019280  0.268487     1.039256         0.668253
 327          0 -0.919030 -0.589690     1.324766        -0.007725
 364          0 -0.019280  0.268487    -1.530333        -0.007725
 197          0  2.679969 -0.589690    -0.673803         1.344231
 372          0  0.880469  0.268487    -1.244823         1.344231
 443          0 -0.919030 -0.589690    -0.102784        -0.683704
 146          0 -0.019280  1.126663    -1.244823        -1.359682
 398          0 -0.919030 -0.589690    -0.959313        -1.359682
 379          0 -0.919030 -0.589690    -1.244823         1.344231
 400          0  1.780219 -0.589690    -0.959313        -0.007725
 371          0 -0.019280  1.126663    -1.244823        -0.007725
 394          0 -0.919030 -0.589690    -0.959313        -1.359682
 465          0 -0.919030 -0.589690     0.182726         1.344231
 665          1 -0.019280  0.268487    -0.673803         1.344231
 696          0 -0.019280  1.126663    -0.388293        -0.007725
 643          0 -0.919030 -0.589690    -0.959313         0.668253
 618          0 -0.919030 -0.589690    -0.959313        -1.359682
 635          0  0.880469  0.268487    -0.959313        -1.359682
 417          1 -0.919030 -0.589690    -0.673803        -0.007725
 514          0 -0.019280  0.268487     1.039256         1.344231
 249          0  0.880469  0.268487     0.182726        -1.359682
 647          0  0.880469 -0.589690    -0.959313        -0.007725
 157          0 -0.919030 -0.589690    -0.959313        -0.683704
 457          0 -0.919030 -0.589690    -0.102784         1.344231
 ..         ...       ...       ...          ...              ...
 324          0 -0.019280 -0.589690     1.324766        -1.359682
 657          0  0.880469  0.268487    -0.673803        -0.007725
 525          0  1.780219 -0.589690     1.039256         1.344231
 429          0 -0.919030 -0.589690    -0.388293        -0.007725
 522          0 -0.019280  0.268487     1.039256        -0.007725
 456          1 -0.919030 -0.589690    -0.102784        -0.007725
 285          0 -0.019280 -0.589690     0.753746         0.668253
 164          1  0.880469 -0.589690    -0.959313        -1.359682
 11           0  2.679969 -0.589690     0.182726        -0.683704
 268          0 -0.019280  2.843016     0.468236        -1.359682
 181          0 -0.019280  1.126663    -0.959313         1.344231
 631          0 -0.919030 -0.589690    -0.959313        -0.007725
 471          0 -0.019280  1.126663     0.182726        -0.683704
 137          0 -0.919030 -0.589690    -1.244823         1.344231
 14           0 -0.919030 -0.589690     0.182726        -0.007725
 626          0 -0.019280  1.126663    -0.959313         0.668253
 414          1 -0.919030 -0.589690    -0.673803         1.344231
 235          0 -0.019280  1.126663    -0.102784         0.668253
 560          0 -0.019280  1.126663     1.610276        -0.007725
 186          0  0.880469 -0.589690    -0.673803        -0.683704
 574          1 -0.919030 -0.589690    -1.530333        -1.359682
 550          0  0.880469  0.268487     1.324766         0.668253
 124          0 -0.919030 -0.589690    -1.530333        -0.007725
 676          1 -0.919030 -0.589690    -0.388293        -0.007725
 632          0 -0.919030 -0.589690    -0.959313         0.668253
 58           0  1.780219 -0.589690     0.753746        -0.007725
 90           0 -0.019280  1.126663     1.324766        -0.007725
 538          1 -0.919030 -0.589690     1.324766         1.344231
 418          0 -0.919030 -0.589690    -0.673803        -0.007725
 446          0 -0.919030 -0.589690    -0.102784         1.344231

 [525 rows x 14 columns],
      reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
 183         0         0         0         1                0.040034
 661         0         1         0         0               -0.654143
 395         0         0         0         1                0.190942
 536         1         0         0         0               -1.574681
 53          0         0         0         1               -1.574681
 672         1         0         0         0               -1.574681
 361         1         0         0         0                0.190942
 107         0         0         0         1                0.568211
 233         1         0         0         0               -0.654143
 223         0         0         0         1                1.036026
 426         0         0         0         1                0.387122
 450         0         0         0         1               -0.654143
 2           0         0         0         1               -0.654143
 346         0         0         0         1               -0.654143
 39          0         0         0         1                0.568211
 210         0         0         0         1               -1.016322
 279         1         0         0         0                0.356940
 566         0         0         0         1                0.040034
 1           0         0         0         0               -1.574681
 556         0         0         0         1                1.036026
 238         1         0         0         0               -1.574681
 470         0         0         0         1                0.356940
 638         0         0         0         1               -0.654143
 241         0         0         1         0               -0.654143
 247         0         0         0         1                1.005844
 493         0         0         0         1                1.036026
 294         0         0         0         0                0.387122
 109         0         0         0         1                2.092381
 123         0         0         0         1               -1.574681
 427         1         0         0         0                2.213108
 ..        ...       ...       ...       ...                     ...
 512         0         0         0         1               -1.574681
 207         0         0         1         0               -0.654143
 275         0         0         0         1                1.036026
 293         0         0         0         0               -1.574681
 21          1         0         0         0               -0.654143
 573         0         0         0         1               -0.654143
 609         0         0         0         1                0.190942
 323         1         0         0         0               -1.016322
 341         0         0         0         1               -0.654143
 4           0         0         0         1                1.005844
 219         0         0         0         1                2.092381
 225         1         0         0         0               -0.654143
 552         0         0         0         1                0.040034
 339         1         0         0         0                0.040034
 345         1         0         0         0                0.356940
 399         0         0         0         1                2.092381
 410         0         0         1         0                0.568211
 667         0         0         1         0                0.040034
 406         0         0         0         0                0.356940
 652         0         0         1         0                1.005844
 481         0         0         0         1               -0.654143
 194         1         0         0         0                0.356940
 527         0         0         0         1               -0.503235
 483         0         0         0         1               -1.574681
 291         0         0         0         1                1.005844
 484         0         0         0         1                1.005844
 526         1         0         0         0                0.040034
 699         0         0         0         1                1.036026
 127         0         0         0         1               -1.574681
 494         0         0         0         1                0.568211

      Distance to Work       Age  Daily Work Load Average  Body Mass Index  \
 183         -0.263140 -1.320435                 1.786584        -0.643782
 661         -0.533522  0.562059                -0.637953        -1.114186
 395         -1.277074  0.091435                -0.685486         0.532229
 536         -1.344669  0.091435                -0.082083         0.297027
 53          -1.344669  0.091435                -0.758273         0.297027
 672         -1.141882  2.130803                -0.637953         1.002633
 361         -1.277074  0.091435                 1.456728         0.532229
 107          1.359154 -0.065439                -0.262439        -0.878984
 233          1.426749  0.248310                 2.644155         1.002633
 223          0.074838  0.562059                 2.644155        -0.408580
 426         -0.330735  1.660180                -0.643304         1.237836
 450          1.426749  0.248310                -0.446195         1.002633
 2            1.426749  0.248310                -0.806331         1.002633
 346          1.426749  0.248310                -0.879469         1.002633
 39           1.359154 -0.065439                -1.647399        -0.878984
 210         -1.209478 -0.379188                 2.677510        -0.408580
 279         -0.330735  0.718933                 0.560476        -0.878984
 566         -0.263140 -1.320435                 0.218718        -0.643782
 1           -1.141882  2.130803                -0.806331         1.002633
 556          0.074838  0.562059                 0.218718        -0.408580
 238         -1.344669  0.091435                 0.087771         0.297027
 470         -0.330735  0.718933                -1.037971        -0.878984
 638          1.426749  0.248310                -1.240355         1.002633
 241         -0.263140 -1.006686                 0.087771        -1.819793
 247          0.412816 -0.536062                 0.087771         0.767431
 493          0.074838  0.562059                -0.550213        -0.408580
 294         -0.330735  1.660180                -0.169648         1.237836
 109          1.494345 -1.320435                -0.262439         0.061825
 123         -1.344669  0.091435                 0.919937         0.297027
 427         -0.871500 -0.849811                -0.643304        -0.408580
 ..                ...       ...                      ...              ...
 512         -1.344669  0.091435                 0.326336         0.297027
 207          1.426749  0.248310                 2.677510         1.002633
 275          0.074838  0.562059                 0.560476        -0.408580

In [24]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(525, 14) (525,)
(175, 14) (175,)

In [25]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, shuffle=True, random_state=20)

In [26]:
y_test.shape

(140,)

In [27]:
#Fitting the Model and Assessing it's accuracy
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [28]:
##training the model
reg = LogisticRegression()

In [29]:
reg.fit(x_train, y_train)

//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
reg.score(x_train, y_train)

0.7714285714285715

In [31]:
##Manually check the accuracy
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [32]:
np.sum(model_outputs == y_train)/model_outputs.shape[0]  #the accuracy from the model is correct!

0.7714285714285715

In [33]:
#Creating a Summary Table with the coefficient and Intercept
reg.intercept_

array([-1.47082548])

In [34]:
reg.coef_

array([[ 2.62614283,  0.84432   ,  2.93971875,  0.67771914,  0.60695978,
        -0.00741802, -0.16862442, -0.00383568,  0.26749958, -0.23085763,
         0.35572764, -0.28559431,  0.16145652, -0.08257256]])

In [35]:
feature_name = unscaled_inputs.columns.values

In [36]:
summary_table = pd.DataFrame(columns=['Feature name'], data=feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

               Feature name  Coefficient
0                  reason_1     2.626143
1                  reason_2     0.844320
2                  reason_3     2.939719
3                  reason_4     0.677719
4    Transportation Expense     0.606960
5          Distance to Work    -0.007418
6                       Age    -0.168624
7   Daily Work Load Average    -0.003836
8           Body Mass Index     0.267500
9                 Education    -0.230858
10                 Children     0.355728
11                     Pets    -0.285594
12              Month Value     0.161457
13          Day of the Week    -0.082573

In [37]:
##Adding interception at the first place
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

               Feature name  Coefficient
0                 Intercept    -1.470825
1                  reason_1     2.626143
2                  reason_2     0.844320
3                  reason_3     2.939719
4                  reason_4     0.677719
5    Transportation Expense     0.606960
6          Distance to Work    -0.007418
7                       Age    -0.168624
8   Daily Work Load Average    -0.003836
9           Body Mass Index     0.267500
10                Education    -0.230858
11                 Children     0.355728
12                     Pets    -0.285594
13              Month Value     0.161457
14          Day of the Week    -0.082573

In [38]:
#Interpreting the coefficients for our Problem
summary_table['odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

               Feature name  Coefficient  odds_ratio
0                 Intercept    -1.470825    0.229736
1                  reason_1     2.626143   13.820360
2                  reason_2     0.844320    2.326395
3                  reason_3     2.939719   18.910527
4                  reason_4     0.677719    1.969381
5    Transportation Expense     0.606960    1.834845
6          Distance to Work    -0.007418    0.992609
7                       Age    -0.168624    0.844826
8   Daily Work Load Average    -0.003836    0.996172
9           Body Mass Index     0.267500    1.306693
10                Education    -0.230858    0.793852
11                 Children     0.355728    1.427219
12                     Pets    -0.285594    0.751567
13              Month Value     0.161457    1.175221
14          Day of the Week    -0.082573    0.920745

In [39]:
summary_table.sort_values('odds_ratio', ascending=False)

               Feature name  Coefficient  odds_ratio
3                  reason_3     2.939719   18.910527
1                  reason_1     2.626143   13.820360
2                  reason_2     0.844320    2.326395
4                  reason_4     0.677719    1.969381
5    Transportation Expense     0.606960    1.834845
11                 Children     0.355728    1.427219
9           Body Mass Index     0.267500    1.306693
13              Month Value     0.161457    1.175221
8   Daily Work Load Average    -0.003836    0.996172
6          Distance to Work    -0.007418    0.992609
14          Day of the Week    -0.082573    0.920745
7                       Age    -0.168624    0.844826
10                Education    -0.230858    0.793852
12                     Pets    -0.285594    0.751567
0                 Intercept    -1.470825    0.229736

#Interpreting the coefficients of the Logistic Regression
1. important values 3,1,2,4,5,11,9 & 10 Education,12 Pets
2. unimportant variables: 13,8,6,14
3. 5 reasons variable, 0-no reason(baseline model-when no reason is given), 1-various diseases, 2-pregnacy and giving birth, 3-poisioning, 4-light diseases
*poisoning: The weight means the odds of someone being excessively absent after being poisoned are 20 times higher than when no reason was reported.
*various diseases: the normal absenteeism case, you got sick, you skipped work. A person who has reported this is 14 times more likely to be excessively absent than a person who didn't specify a reason
*Pregnacy and giving birth: pregnacy check and come back to work, from time to time, there's some emergencies, but the odds ratio is only 2.3 times more likely to be excessively absent than the base model.

4. Transportation Expense: is one of our standardized variables, we don't have direct interpretability of it. the odds ratio implies that for 1 standardized unit or for 1 standard deviation increase in transportation expense, it is close to twice as likely to be excessively absent
5. Pet: for each additional standardized unit of pet, the odds are 1-0.751567 = 25% lower than the base model(no pet) explanation: maybe if you have many pets, you are probably not taking care of them on your own, you will have someone to take pets to the doctor if something is wrong.
6. intercept: no meaning, in ML, you can say the intercept/Bias 'calibrates' the model.