In [1]:
#Standardizing only the Numerical Variables(Creating a custom Scaler)

#Import libraries
import pandas as pd
import numpy as np

In [2]:
#Load the data
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Month Value,Day of the Week,Absenteeism Time in Hours
0,0,0,0,1,289,36,33,239.554,30,0,2,1,7,1,4
1,0,0,0,0,118,13,50,239.554,31,0,1,0,7,1,0
2,0,0,0,1,179,51,38,239.554,31,0,0,0,7,2,2
3,1,0,0,0,279,5,39,239.554,24,0,2,0,7,3,4
4,0,0,0,1,289,36,33,239.554,30,0,2,1,7,3,2
5,0,0,0,1,179,51,38,239.554,31,0,0,0,7,4,2
6,0,0,0,1,361,52,28,239.554,27,0,1,4,7,4,8
7,0,0,0,1,260,50,36,239.554,23,0,4,0,7,4,4
8,0,0,1,0,155,12,34,239.554,25,0,2,0,7,0,40
9,0,0,0,1,235,11,37,239.554,29,1,1,1,7,0,8
10,1,0,0,0,260,50,36,239.554,23,0,4,0,7,0,8
11,1,0,0,0,260,50,36,239.554,23,0,4,0,7,1,8
12,1,0,0,0,260,50,36,239.554,23,0,4,0,7,2,8
13,1,0,0,0,179,51,38,239.554,31,0,0,0,7,2,1
14,0,0,0,1,179,51,38,239.554,31,0,0,0,7,2,4
15,1,0,0,0,246,25,41,239.554,23,0,0,0,7,4,8
16,0,0,0,1,179,51,38,239.554,31,0,0,0,7,4,2
17,0,0,1,0,179,51,38,239.554,31,0,0,0,7,0,8
18,1,0,0,0,189,29,33,239.554,25,0,2,2,7,3,8
19,0,0,0,1,248,25,47,205.917,32,0,2,1,8,2,2
20,1,0,0,0,330,16,28,205.917,25,1,0,0,8,2,8
21,1,0,0,0,179,51,38,205.917,31,0,0,0,8,0,1
22,1,0,0,0,361,52,28,205.917,27,0,1,4,8,0,40
23,0,0,0,1,260,50,36,205.917,23,0,4,0,8,4,4
24,0,0,1,0,289,36,33,205.917,30,0,2,1,8,0,8
25,0,0,0,1,361,52,28,205.917,27,0,1,4,8,0,7
26,0,0,0,1,289,36,33,205.917,30,0,2,1,8,1,1
27,0,0,0,1,157,27,29,205.917,22,0,0,0,8,2,4
28,0,0,1,0,289,36,33,205.917,30,0,2,1,8,2,8
29,0,0,0,1,179,51,38,205.917,31,0,0,0,8,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,155,12,34,246.288,25,0,2,0,4,1,4
671,0,0,1,0,225,26,28,246.288,24,0,1,2,4,3,8
672,1,0,0,0,118,13,50,246.288,31,0,1,0,4,3,2
673,0,0,0,1,179,26,30,246.288,19,1,0,0,4,4,2
674,0,0,0,1,235,11,37,237.656,29,1,1,1,5,0,8
675,0,0,1,0,225,15,41,237.656,28,1,2,2,5,2,3
676,0,0,0,1,235,16,32,237.656,25,1,0,0,5,2,2
677,1,0,0,0,118,10,37,237.656,28,0,0,0,5,2,3
678,0,0,0,1,235,20,43,237.656,38,0,1,0,5,2,8
679,1,0,0,0,179,26,30,237.656,19,1,0,0,5,3,1
680,0,0,0,1,291,31,40,237.656,25,0,1,1,5,3,2
681,1,0,0,0,225,15,41,237.656,28,1,2,2,5,3,8
682,0,0,1,0,300,26,43,237.656,25,0,2,1,5,4,64
683,0,0,0,1,225,15,41,237.656,28,1,2,2,5,4,8
684,0,0,0,1,179,26,30,237.656,19,1,0,0,5,4,2
685,0,0,0,1,118,13,50,237.656,31,0,1,0,5,0,2
686,1,0,0,0,118,13,50,237.656,31,0,1,0,5,1,3
687,0,0,0,1,118,10,37,237.656,28,0,0,0,5,1,1
688,0,0,0,0,118,13,50,237.656,31,0,1,0,5,1,0
689,0,0,0,1,179,26,30,237.656,19,1,0,0,5,2,2
690,0,0,0,0,378,49,36,237.656,21,0,2,4,5,2,0
691,0,1,0,0,179,22,40,237.656,22,1,2,0,5,4,1
692,1,0,0,0,155,12,34,237.656,25,0,2,0,5,0,48
693,1,0,0,0,235,16,32,237.656,25,1,0,0,5,0,8
694,0,0,0,1,291,31,40,237.656,25,0,1,1,5,2,8
695,1,0,0,0,179,22,40,237.656,22,1,2,0,5,2,8
696,1,0,0,0,225,26,28,237.656,24,0,1,2,5,2,3
697,1,0,0,0,330,16,28,237.656,25,1,0,0,5,3,8
698,0,0,0,1,235,16,32,237.656,25,1,0,0,5,3,2
699,0,0,0,1,291,31,40,237.656,25,0,1,1,5,3,2

In [4]:
#Targets
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head(10)

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Month Value,Day of the Week,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,289,36,33,239.554,30,0,2,1,7,1,4,1
1,0,0,0,0,118,13,50,239.554,31,0,1,0,7,1,0,0
2,0,0,0,1,179,51,38,239.554,31,0,0,0,7,2,2,0
3,1,0,0,0,279,5,39,239.554,24,0,2,0,7,3,4,1
4,0,0,0,1,289,36,33,239.554,30,0,2,1,7,3,2,0
5,0,0,0,1,179,51,38,239.554,31,0,0,0,7,4,2,0
6,0,0,0,1,361,52,28,239.554,27,0,1,4,7,4,8,1
7,0,0,0,1,260,50,36,239.554,23,0,4,0,7,4,4,1
8,0,0,1,0,155,12,34,239.554,25,0,2,0,7,0,40,1
9,0,0,0,1,235,11,37,239.554,29,1,1,1,7,0,8,1

In [8]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Distance to Work',
                                            'Daily Work Load Average','Day of the Week'], axis=1)

In [10]:
data_with_targets is data_preprocessed

False

In [11]:
data_with_targets.head()

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Month Value,Excessive Absenteeism
0,0,0,0,1,289,33,30,0,2,1,7,1
1,0,0,0,0,118,50,31,0,1,0,7,0
2,0,0,0,1,179,38,31,0,0,0,7,0
3,1,0,0,0,279,39,24,0,2,0,7,1
4,0,0,0,1,289,33,30,0,2,1,7,0

In [12]:
#Selecting the inputs for the logistic regression
data_with_targets.shape

(700, 12)

In [13]:
unscaled_inputs = data_with_targets.iloc[:, :-1]
unscaled_inputs

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Month Value
0,0,0,0,1,289,33,30,0,2,1,7
1,0,0,0,0,118,50,31,0,1,0,7
2,0,0,0,1,179,38,31,0,0,0,7
3,1,0,0,0,279,39,24,0,2,0,7
4,0,0,0,1,289,33,30,0,2,1,7
5,0,0,0,1,179,38,31,0,0,0,7
6,0,0,0,1,361,28,27,0,1,4,7
7,0,0,0,1,260,36,23,0,4,0,7
8,0,0,1,0,155,34,25,0,2,0,7
9,0,0,0,1,235,37,29,1,1,1,7
10,1,0,0,0,260,36,23,0,4,0,7
11,1,0,0,0,260,36,23,0,4,0,7
12,1,0,0,0,260,36,23,0,4,0,7
13,1,0,0,0,179,38,31,0,0,0,7
14,0,0,0,1,179,38,31,0,0,0,7
15,1,0,0,0,246,41,23,0,0,0,7
16,0,0,0,1,179,38,31,0,0,0,7
17,0,0,1,0,179,38,31,0,0,0,7
18,1,0,0,0,189,33,25,0,2,2,7
19,0,0,0,1,248,47,32,0,2,1,8
20,1,0,0,0,330,28,25,1,0,0,8
21,1,0,0,0,179,38,31,0,0,0,8
22,1,0,0,0,361,28,27,0,1,4,8
23,0,0,0,1,260,36,23,0,4,0,8
24,0,0,1,0,289,33,30,0,2,1,8
25,0,0,0,1,361,28,27,0,1,4,8
26,0,0,0,1,289,33,30,0,2,1,8
27,0,0,0,1,157,29,22,0,0,0,8
28,0,0,1,0,289,33,30,0,2,1,8
29,0,0,0,1,179,38,31,0,0,0,8
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,155,34,25,0,2,0,4
671,0,0,1,0,225,28,24,0,1,2,4
672,1,0,0,0,118,50,31,0,1,0,4
673,0,0,0,1,179,30,19,1,0,0,4
674,0,0,0,1,235,37,29,1,1,1,5
675,0,0,1,0,225,41,28,1,2,2,5
676,0,0,0,1,235,32,25,1,0,0,5
677,1,0,0,0,118,37,28,0,0,0,5
678,0,0,0,1,235,43,38,0,1,0,5
679,1,0,0,0,179,30,19,1,0,0,5
680,0,0,0,1,291,40,25,0,1,1,5
681,1,0,0,0,225,41,28,1,2,2,5
682,0,0,1,0,300,43,25,0,2,1,5
683,0,0,0,1,225,41,28,1,2,2,5
684,0,0,0,1,179,30,19,1,0,0,5
685,0,0,0,1,118,50,31,0,1,0,5
686,1,0,0,0,118,50,31,0,1,0,5
687,0,0,0,1,118,37,28,0,0,0,5
688,0,0,0,0,118,50,31,0,1,0,5
689,0,0,0,1,179,30,19,1,0,0,5
690,0,0,0,0,378,36,21,0,2,4,5
691,0,1,0,0,179,40,22,1,2,0,5
692,1,0,0,0,155,34,25,0,2,0,5
693,1,0,0,0,235,32,25,1,0,0,5
694,0,0,0,1,291,40,25,0,1,1,5
695,1,0,0,0,179,40,22,1,2,0,5
696,1,0,0,0,225,28,24,0,1,2,5
697,1,0,0,0,330,28,25,1,0,0,5
698,0,0,0,1,235,32,25,1,0,0,5
699,0,0,0,1,291,40,25,0,1,1,5

In [14]:
#Standardizing the data
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [16]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [17]:
#columns_to_scale = ['Transportation Expense', 'Distance to Work', 'Age',
       #'Daily Work Load Average', 'Body Mass Index','Children', 
                   # 'Pets', 'Month Value', 'Day of the Week']

In [18]:
columns_to_omit = ['reason_1', 'reason_2', 'reason_3', 'reason_4','Education']

In [19]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [20]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [21]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets', 'Month Value'],
             copy=None, with_mean=None, with_std=None)

In [22]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [23]:
scaled_inputs

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Month Value
0,0,0,0,1,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.182726
1,0,0,0,0,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,0.182726
2,0,0,0,1,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.182726
3,1,0,0,0,0.854936,0.405184,-0.643782,0,0.880469,-0.589690,0.182726
4,0,0,0,1,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.182726
5,0,0,0,1,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.182726
6,0,0,0,1,2.092381,-1.320435,0.061825,0,-0.019280,2.843016,0.182726
7,0,0,0,1,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690,0.182726
8,0,0,1,0,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690,0.182726
9,0,0,0,1,0.190942,0.091435,0.532229,1,-0.019280,0.268487,0.182726
10,1,0,0,0,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690,0.182726
11,1,0,0,0,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690,0.182726
12,1,0,0,0,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690,0.182726
13,1,0,0,0,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.182726
14,0,0,0,1,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.182726
15,1,0,0,0,0.356940,0.718933,-0.878984,0,-0.919030,-0.589690,0.182726
16,0,0,0,1,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.182726
17,0,0,1,0,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.182726
18,1,0,0,0,-0.503235,-0.536062,-0.408580,0,0.880469,1.126663,0.182726
19,0,0,0,1,0.387122,1.660180,1.237836,0,0.880469,0.268487,0.468236
20,1,0,0,0,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690,0.468236
21,1,0,0,0,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.468236
22,1,0,0,0,2.092381,-1.320435,0.061825,0,-0.019280,2.843016,0.468236
23,0,0,0,1,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690,0.468236
24,0,0,1,0,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.468236
25,0,0,0,1,2.092381,-1.320435,0.061825,0,-0.019280,2.843016,0.468236
26,0,0,0,1,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.468236
27,0,0,0,1,-0.986140,-1.163560,-1.114186,0,-0.919030,-0.589690,0.468236
28,0,0,1,0,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.468236
29,0,0,0,1,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.468236
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690,-0.673803
671,0,0,1,0,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663,-0.673803
672,1,0,0,0,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,-0.673803
673,0,0,0,1,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690,-0.673803
674,0,0,0,1,0.190942,0.091435,0.532229,1,-0.019280,0.268487,-0.388293
675,0,0,1,0,0.040034,0.718933,0.297027,1,0.880469,1.126663,-0.388293
676,0,0,0,1,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690,-0.388293
677,1,0,0,0,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690,-0.388293
678,0,0,0,1,0.190942,1.032682,2.649049,0,-0.019280,-0.589690,-0.388293
679,1,0,0,0,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690,-0.388293
680,0,0,0,1,1.036026,0.562059,-0.408580,0,-0.019280,0.268487,-0.388293
681,1,0,0,0,0.040034,0.718933,0.297027,1,0.880469,1.126663,-0.388293
682,0,0,1,0,1.171843,1.032682,-0.408580,0,0.880469,0.268487,-0.388293
683,0,0,0,1,0.040034,0.718933,0.297027,1,0.880469,1.126663,-0.388293
684,0,0,0,1,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690,-0.388293
685,0,0,0,1,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,-0.388293
686,1,0,0,0,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,-0.388293
687,0,0,0,1,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690,-0.388293
688,0,0,0,0,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,-0.388293
689,0,0,0,1,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690,-0.388293
690,0,0,0,0,2.348925,-0.065439,-1.349389,0,0.880469,2.843016,-0.388293
691,0,1,0,0,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690,-0.388293
692,1,0,0,0,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690,-0.388293
693,1,0,0,0,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690,-0.388293
694,0,0,0,1,1.036026,0.562059,-0.408580,0,-0.019280,0.268487,-0.388293
695,1,0,0,0,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690,-0.388293
696,1,0,0,0,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663,-0.388293
697,1,0,0,0,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690,-0.388293
698,0,0,0,1,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690,-0.388293
699,0,0,0,1,1.036026,0.562059,-0.408580,0,-0.019280,0.268487,-0.388293

In [24]:
#Splitting the date for training and testing
from sklearn.model_selection import train_test_split

In [25]:
train_test_split(scaled_inputs, targets)

[     reason_1  reason_2  reason_3  reason_4  Transportation Expense       Age  \
 590         0         0         0         1               -0.654143  0.248310
 475         0         0         0         1                1.005844 -0.536062
 229         1         0         0         0                0.190942  0.091435
 150         0         0         0         1                0.040034 -1.320435
 621         0         0         0         1                0.387122  1.660180
 408         0         0         0         1               -0.654143  0.248310
 108         0         0         0         1                0.040034 -1.320435
 353         1         0         0         0                0.190942  0.091435
 523         1         0         0         0                2.213108 -0.849811
 647         0         0         0         1               -1.574681  1.503305
 140         0         0         0         1               -1.016322 -0.379188
 525         1         0         0         0                2.213108 -0.849811
 295         1         0         0         0               -0.654143 -1.006686
 279         1         0         0         0                0.356940  0.718933
 593         0         0         0         1               -0.654143  0.248310
 301         0         0         1         0                1.005844 -0.536062
 503         0         0         0         1                0.040034 -1.320435
 393         0         0         0         1                0.568211 -0.065439
 661         0         1         0         0               -0.654143  0.562059
 249         0         0         1         0                1.005844 -0.536062
 272         0         0         1         0                1.005844 -0.536062
 300         0         0         0         0                0.190942  1.032682
 399         0         0         0         1                2.092381 -1.320435
 613         0         0         0         1                0.387122  1.660180
 136         0         0         0         1                1.005844 -0.536062
 519         0         0         0         1                2.213108 -0.849811
 334         1         0         0         0                0.568211 -0.065439
 299         1         0         0         0               -0.654143 -1.006686
 508         1         0         0         0                0.190942 -0.692937
 62          0         0         0         1               -0.654143  0.248310
 ..        ...       ...       ...       ...                     ...       ...
 337         0         0         0         0                0.854936  0.405184
 118         0         0         0         1               -0.578689 -1.477309
 360         0         0         0         1               -1.016322 -0.379188
 338         0         0         0         1               -0.654143  0.248310
 135         0         0         0         1                0.040034 -1.320435
 527         0         0         0         1               -0.503235 -0.536062
 50          0         0         0         0                0.568211 -0.065439
 383         0         0         0         1                1.036026  0.562059
 471         1         0         0         0                0.040034 -1.320435
 32          0         0         0         1                0.190942  0.091435
 644         0         0         0         1               -0.654143 -1.006686
 580         0         0         0         1               -0.654143 -1.006686
 605         0         0         0         1               -0.654143  0.248310
 60          0         0         0         1               -0.654143  0.248310
 72          0         0         0         1               -0.654143  0.248310
 562         0         0         1         0               -0.654143  0.562059
 570         1         0         0         0               -0.654143 -1.006686
 515         0         0         0         1                0.040034 -1.320435
 662         0         0         0         1               -1.574681  2.130803
 581         0         0         0         1               -0.654143  0.248310
 122         0         0         0         1                0.040034 -1.320435
 18          1         0         0         0               -0.503235 -0.536062
 97          0         0         0         1                1.036026  0.562059
 384         1         0         0         0               -0.986140 -1.163560
 395         0         0         0         1                0.190942  0.091435
 84          0         0         0         1                1.036026  0.562059
 89          1         0         0         0               -1.016322 -0.379188
 246         0         0         0         1                2.092381 -1.320435
 52          0         0         0         1                0.040034 -1.320435
 157         0         0         1         0               -0.986140 -1.163560

      Body Mass Index  Education  Children      Pets  Month Value
 590         1.002633          0 -0.919030 -0.589690    -1.244823
 475         0.767431          0  0.880469  0.268487     0.182726
 229         0.532229          1 -0.019280  0.268487    -0.102784
 150        -0.643782          0 -0.019280  1.126663    -1.244823
 621         1.237836          0  0.880469  0.268487    -0.959313
 408         1.002633          0 -0.919030 -0.589690    -0.959313
 108        -0.643782          0 -0.019280  1.126663     1.610276
 353         0.532229          1 -0.019280  0.268487     1.610276
 523        -0.408580          0  1.780219 -0.589690     1.039256
 647        -0.408580          0  0.880469 -0.589690    -0.959313
 140        -0.408580          0  0.880469 -0.589690    -1.244823
 525        -0.408580          0  1.780219 -0.589690     1.039256
 295        -1.819793          1 -0.919030 -0.589690     1.039256
 279        -0.878984          0 -0.919030 -0.589690     0.753746
 593         1.002633          0 -0.919030 -0.589690    -1.244823
 301         0.767431          0  0.880469  0.268487     1.039256
 503        -0.643782          0 -0.019280  1.126663     0.753746
 393        -0.878984          0  2.679969 -0.589690    -0.959313
 661        -1.114186          1  0.880469 -0.589690    -0.673803
 249         0.767431          0  0.880469  0.268487     0.182726
 272         0.767431          0  0.880469  0.268487     0.753746
 300         2.649049          0 -0.019280 -0.589690     1.039256
 399         0.061825          0 -0.019280  2.843016    -0.959313
 613         1.237836          0  0.880469  0.268487    -1.244823
 136         0.767431          0  0.880469  0.268487    -1.530333
 519        -0.408580          0  1.780219 -0.589690     1.039256
 334        -0.878984          0  2.679969 -0.589690     1.324766
 299        -1.819793          1 -0.919030 -0.589690     1.039256
 508        -0.408580          1 -0.919030 -0.589690     1.039256
 62          1.002633          0 -0.919030 -0.589690     1.039256
 ..               ...        ...       ...       ...          ...
 337        -0.643782          0  0.880469 -0.589690     1.324766
 118        -1.349389          0 -0.919030 -0.589690    -1.530333
 360        -0.408580          0  0.880469 -0.589690    -1.530333
 338         1.002633          0 -0.919030 -0.589690     1.324766
 135        -0.643782          0 -0.019280  1.126663    -1.530333
 527        -0.408580          0  0.880469  1.126663     1.039256
 50         -0.878984          0  2.679969 -0.589690     0.753746
 383        -0.408580          0 -0.019280  0.268487    -1.244823
 471        -0.643782          0 -0.019280  1.126663     0.182726
 32          0.532229          1 -0.019280  0.268487     0.468236
 644        -1.819793          1 -0.919030 -0.589690    -0.959313
 580        -1.819793          1 -0.919030 -0.589690    -1.530333
 605         1.002633          0 -0.919030 -0.589690    -1.244823
 60          1.002633          0 -0.919030 -0.589690     0.753746
 72          1.002633          0 -0.919030 -0.589690     1.039256
 562        -1.114186          1  0.880469 -0.589690     1.610276
 570        -1.819793          1 -0.919030 -0.589690    -1.530333
 515        -0.643782          0 -0.019280  1.126663     1.039256
 662         1.002633          0 -0.019280 -0.589690    -0.673803
 581         1.002633          0 -0.919030 -0.589690    -1.530333
 122        -0.643782          0 -0.019280  1.126663    -1.530333
 18         -0.408580          0  0.880469  1.126663     0.182726
 97         -0.408580          0 -0.019280  0.268487     1.324766
 384        -1.114186          0 -0.919030 -0.589690    -1.244823
 395         0.532229          1 -0.019280  0.268487    -0.959313
 84         -0.408580          0 -0.019280  0.268487     1.324766
 89         -0.408580          0  0.880469 -0.589690     1.324766
 246         0.061825          0 -0.019280  2.843016     0.182726
 52         -0.643782          0 -0.019280  1.126663     0.753746
 157        -1.114186          0 -0.919030 -0.589690    -0.959313

 [525 rows x 11 columns],
      reason_1  reason_2  reason_3  reason_4  Transportation Expense       Age  \
 375         0         0         0         1               -0.654143  0.248310
 472         0         0         0         1               -0.654143  0.248310
 694         0         0         0         1                1.036026  0.562059
 217         1         0         0         0               -0.654143  0.248310
 141         0         0         0         1               -0.503235 -0.536062
 646         0         0         0         1               -0.654143  0.248310
 532         0         0         1         0               -0.654143  0.248310
 687         0         0         0         1               -1.574681  0.091435
 95          0         0         0         1                0.040034 -1.320435
 82          1         0         0         0               -0.654143  0.248310
 406         0         0         0         0                0.356940  0.718933
 258         0         0         0         1                0.568211 -0.065439
 489         0         0         0         1                1.624567 -1.320435
 378         0         0         0         1                0.356940  0.718933
 17          0         0         1         0               -0.654143  0.248310
 428         0         0         0         1               -0.654143 -1.006686
 487         0         0         0         1               -0.654143  0.248310
 11          1         0         0         0                0.568211 -0.065439
 231         1         0         0         0               -1.574681  2.130803
 293         0         0         0         0               -1.574681  2.130803
 611         1         0         0         0                0.040034 -1.320435
 681         1         0         0         0                0.040034  0.718933
 261         1         0         0         0                0.688938 -0.536062
 80          0         0         0         1               -0.654143  0.248310
 166         0         0         0         1                0.568211 -0.065439
 522         0         0         0         1                1.036026  0.562059
 454         0         0         0         1               -1.574681  2.130803
 304         0         0         0         1                0.190942  1.032682
 675         0         0         1         0                0.040034  0.718933
 538         1         0         0         0                0.190942 -0.692937
 ..        ...       ...       ...       ...                     ...       ...
 171         0         0         0         1                0.040034 -1.320435
 351         0         0         0         1               -0.654143  0.248310
 500         0         0         0         1               -0.654143 -1.006686
 403         1         0         0         0               -1.574681  2.130803
 606         1         0         0         0               -0.654143  0.248310
 28          0         0         1         0                1.005844 -0.536062
 236         0         0         1         0               -1.016322 -0.379188
 557         0         0         0         1                0.040034 -1.320435
 257         1         0         0         0                1.171843  1.032682
 127         0         0         0         1               -1.574681  0.091435
 634         1         0         0         0               -0.654143  0.248310
 240         0         0         0         1                1.624567 -1.320435
 172         1         0         0         0                0.854936  0.405184
 126         0         0         0         1               -1.574681  0.091435
 643         0         0         0         1               -0.654143  0.248310
 179         1         0         0         0               -0.654143  0.248310
 98          0         0         0         1                0.387122  1.660180
 110         0         0         0         1               -1.574681  0.091435
 651         1         0         0         0               -0.654143 -1.006686
 541         0         0         0         1                1.036026  0.562059
 622         1         0         0         0                0.085306  3.385799
 407         0         0         0         0               -1.574681  2.130803
 539         0         0         0         1                0.040034 -1.320435
 69          0         0         0         1                0.040034 -1.320435
 91          0         0         1         0               -0.654143  0.562059
 306         0         0         0         1               -1.574681  2.130803
 660         1         0         0         0                2.213108 -0.849811
 76          0         0         0         1                0.040034 -1.320435
 653         0         0         0         1                2.213108 -0.849811
 437         0         0         0         1               -0.654143 -1.006686

      Body Mass Index  Education  Children      Pets  Month Value
 375         1.002633          0 -0.919030 -0.589690    -1.244823
 472         1.002633          0 -0.919030 -0.589690     0.182726
 694        -0.408580          0 -0.019280  0.268487    -0.388293
 217         1.002633          0 -0.919030 -0.589690    -0.388293
 141        -0.408580          0  0.880469  1.126663    -1.244823
 646         1.002633          0 -0.919030 -0.589690    -0.959313
 532         1.002633          0 -0.919030 -0.589690     1.324766
 687         0.297027          0 -0.919030 -0.589690    -0.388293
 95         -0.643782          0 -0.019280  1.126663     1.324766
 82          1.002633          0 -0.919030 -0.589690     1.324766
 406        -0.878984          0 -0.919030 -0.589690    -0.959313
 258        -0.878984          0  2.679969 -0.589690     0.468236
 489        -0.408580          1 -0.919030 -0.589690     0.468236
 378        -0.878984          0 -0.919030 -0.589690    -1.244823
 17          1.002633          0 -0.919030 -0.589690     0.182726
 428        -1.819793          1 -0.919030 -0.589690    -0.388293
 487         1.002633          0 -0.919030 -0.589690     0.468236
 11         -0.878984          0  2.679969 -0.589690     0.182726
 231         1.002633          0 -0.019280 -0.589690    -0.102784
 293         1.002633          0 -0.019280 -0.589690     1.039256
 611        -0.643782          0 -0.019280  1.126663    -1.244823
 681         0.297027          1  0.880469  1.126663    -0.388293
 261        -0.408580          1 -0.919030 -0.589690     0.468236
 80          1.002633          0 -0.919030 -0.589690     1.324766
 166        -0.878984          0  2.679969 -0.589690    -0.959313
 522        -0.408580          0 -0.019280  0.268487     1.039256
 454         1.002633          0 -0.019280 -0.589690    -0.102784
 304         2.649049          0 -0.019280 -0.589690     1.039256
 675         0.297027          1  0.880469  1.126663    -0.388293
 538        -0.408580          1 -0.919030 -0.589690     1.324766
 ..               ...        ...       ...       ...          ...
 171        -0.643782          0 -0.019280  1.126663    -0.959313
 351         1.002633          0 -0.919030 -0.589690     1.610276
 500        -1.819793          1 -0.919030 -0.589690     0.753746
 403         1.002633          0 -0.019280 -0.589690    -0.959313
 606         1.002633          0 -0.919030 -0.589690    -1.244823
 28          0.767431          0  0.880469  0.268487     0.468236
 236        -0.408580          0  0.880469 -0.589690     0.182726
 557        -0.643782          0 -0.019280  1.126663     1.610276
 257        -0.408580          0  0.880469  0.268487     0.468236
 127         0.297027          0 -0.919030 -0.589690    -1.530333
 634         1.002633          0 -0.919030 -0.589690    -0.959313
 240        -0.408580          1 -0.919030 -0.589690     0.182726
 172        -0.643782          0  0.880469 -0.589690    -0.959313
 126         0.297027          0 -0.919030 -0.589690    -1.530333
 643         1.002633          0 -0.919030 -0.589690    -0.959313
 179         1.002633          0 -0.919030 -0.589690    -0.959313
 98          1.237836          0  0.880469  0.268487     1.610276
 110         0.297027          0 -0.919030 -0.589690     1.610276
 651        -1.819793          1 -0.919030 -0.589690    -0.959313
 541        -0.408580          0 -0.019280  0.268487     1.324766
 622        -1.114186          0  0.880469  0.268487    -0.959313
 407         1.002633          0 -0.019280 -0.589690    -0.959313
 539        -0.643782          0 -0.019280  1.126663     1.324766
 69         -0.643782          0 -0.019280  1.126663     1.039256
 91         -1.114186          1  0.880469 -0.589690     1.324766
 306         1.002633          0 -0.019280 -0.589690     1.039256
 660        -0.408580          0  1.780219 -0.589690    -0.673803
 76         -0.643782          0 -0.019280  1.126663     1.039256
 653        -0.408580          0  1.780219 -0.589690    -0.959313
 437        -1.819793          1 -0.919030 -0.589690    -0.388293

 [175 rows x 11 columns],
 array([0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
        1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
        1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
        0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0]),
 array([0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,

In [26]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(525, 11) (525,)
(175, 11) (175,)

In [27]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, shuffle=True, random_state=20)

In [28]:
y_test.shape

(140,)

In [29]:
#Fitting the Model and Assessing it's accuracy
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [30]:
##training the model
reg = LogisticRegression()

In [31]:
reg.fit(x_train, y_train)

//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [32]:
reg.score(x_train, y_train)

0.775

In [33]:
##Manually check the accuracy
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [34]:
np.sum(model_outputs == y_train)/model_outputs.shape[0]  #the accuracy from the model is correct!

0.775

In [35]:
#Creating a Summary Table with the coefficient and Intercept
reg.intercept_

array([-1.46547112])

In [36]:
reg.coef_

array([[ 2.62749942,  0.86338637,  2.96050661,  0.66390745,  0.59979822,
        -0.17245127,  0.27568526, -0.23452541,  0.34249662, -0.2775137 ,
         0.15493732]])

In [37]:
feature_name = unscaled_inputs.columns.values

In [38]:
summary_table = pd.DataFrame(columns=['Feature name'], data=feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

              Feature name  Coefficient
0                 reason_1     2.627499
1                 reason_2     0.863386
2                 reason_3     2.960507
3                 reason_4     0.663907
4   Transportation Expense     0.599798
5                      Age    -0.172451
6          Body Mass Index     0.275685
7                Education    -0.234525
8                 Children     0.342497
9                     Pets    -0.277514
10             Month Value     0.154937

In [39]:
##Adding interception at the first place
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

              Feature name  Coefficient
0                Intercept    -1.465471
1                 reason_1     2.627499
2                 reason_2     0.863386
3                 reason_3     2.960507
4                 reason_4     0.663907
5   Transportation Expense     0.599798
6                      Age    -0.172451
7          Body Mass Index     0.275685
8                Education    -0.234525
9                 Children     0.342497
10                    Pets    -0.277514
11             Month Value     0.154937

In [40]:
#Interpreting the coefficients for our Problem
summary_table['odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

              Feature name  Coefficient  odds_ratio
0                Intercept    -1.465471    0.230969
1                 reason_1     2.627499   13.839121
2                 reason_2     0.863386    2.371177
3                 reason_3     2.960507   19.307751
4                 reason_4     0.663907    1.942367
5   Transportation Expense     0.599798    1.821751
6                      Age    -0.172451    0.841599
7          Body Mass Index     0.275685    1.317433
8                Education    -0.234525    0.790946
9                 Children     0.342497    1.408460
10                    Pets    -0.277514    0.757665
11             Month Value     0.154937    1.167585

In [41]:
summary_table.sort_values('odds_ratio', ascending=False)

              Feature name  Coefficient  odds_ratio
3                 reason_3     2.960507   19.307751
1                 reason_1     2.627499   13.839121
2                 reason_2     0.863386    2.371177
4                 reason_4     0.663907    1.942367
5   Transportation Expense     0.599798    1.821751
9                 Children     0.342497    1.408460
7          Body Mass Index     0.275685    1.317433
11             Month Value     0.154937    1.167585
6                      Age    -0.172451    0.841599
8                Education    -0.234525    0.790946
10                    Pets    -0.277514    0.757665
0                Intercept    -1.465471    0.230969

Compared to orginal model, simplified model works well. All coefficients are almost the same.

In [42]:
#Testing the model
reg.score(x_test, y_test)

0.75

In [43]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71221976, 0.28778024],
       [0.58760009, 0.41239991],
       [0.44337438, 0.55662562],
       [0.77903962, 0.22096038],
       [0.08458343, 0.91541657],
       [0.33103371, 0.66896629],
       [0.29792496, 0.70207504],
       [0.12956221, 0.87043779],
       [0.78307821, 0.21692179],
       [0.74708659, 0.25291341],
       [0.49514969, 0.50485031],
       [0.22640297, 0.77359703],
       [0.07030984, 0.92969016],
       [0.73504052, 0.26495948],
       [0.30533085, 0.69466915],
       [0.55035881, 0.44964119],
       [0.55027426, 0.44972574],
       [0.53930442, 0.46069558],
       [0.40117774, 0.59882226],
       [0.05320682, 0.94679318],
       [0.69874615, 0.30125385],
       [0.77903962, 0.22096038],
       [0.41634563, 0.58365437],
       [0.41634563, 0.58365437],
       [0.2412915 , 0.7587085 ],
       [0.74317087, 0.25682913],
       [0.51065194, 0.48934806],
       [0.85703303, 0.14296697],
       [0.19934235, 0.80065765],
       [0.77903962, 0.22096038],
       [0.62971577, 0.37028423],
       [0.31683213, 0.68316787],
       [0.31174245, 0.68825755],
       [0.47305759, 0.52694241],
       [0.77903962, 0.22096038],
       [0.46507358, 0.53492642],
       [0.77546993, 0.22453007],
       [0.25610763, 0.74389237],
       [0.59670727, 0.40329273],
       [0.39698373, 0.60301627],
       [0.78656024, 0.21343976],
       [0.54516654, 0.45483346],
       [0.7596912 , 0.2403088 ],
       [0.5611569 , 0.4388431 ],
       [0.17377065, 0.82622935],
       [0.42142868, 0.57857132],
       [0.30538941, 0.69461059],
       [0.71221976, 0.28778024],
       [0.77790972, 0.22209028],
       [0.7938926 , 0.2061074 ],
       [0.42422877, 0.57577123],
       [0.63561337, 0.36438663],
       [0.33103371, 0.66896629],
       [0.72871439, 0.27128561],
       [0.16665264, 0.83334736],
       [0.56600768, 0.43399232],
       [0.11399337, 0.88600663],
       [0.76603645, 0.23396355],
       [0.62829315, 0.37170685],
       [0.61790495, 0.38209505],
       [0.30203861, 0.69796139],
       [0.34090197, 0.65909803],
       [0.70607803, 0.29392197],
       [0.20313854, 0.79686146],
       [0.79043907, 0.20956093],
       [0.7300077 , 0.2699923 ],
       [0.89600113, 0.10399887],
       [0.77546993, 0.22453007],
       [0.26055756, 0.73944244],
       [0.69918168, 0.30081832],
       [0.77546993, 0.22453007],
       [0.67311234, 0.32688766],
       [0.09662446, 0.90337554],
       [0.54254271, 0.45745729],
       [0.40002753, 0.59997247],
       [0.77903962, 0.22096038],
       [0.22136985, 0.77863015],
       [0.27141023, 0.72858977],
       [0.25655446, 0.74344554],
       [0.32955172, 0.67044828],
       [0.75152292, 0.24847708],
       [0.91016537, 0.08983463],
       [0.76603645, 0.23396355],
       [0.24559275, 0.75440725],
       [0.5662996 , 0.4337004 ],
       [0.87737541, 0.12262459],
       [0.29308287, 0.70691713],
       [0.41634563, 0.58365437],
       [0.72586122, 0.27413878],
       [0.31683213, 0.68316787],
       [0.82638206, 0.17361794],
       [0.84738944, 0.15261056],
       [0.77133106, 0.22866894],
       [0.7300077 , 0.2699923 ],
       [0.74708659, 0.25291341],
       [0.14880137, 0.85119863],
       [0.70306858, 0.29693142],
       [0.23583473, 0.76416527],
       [0.75414044, 0.24585956],
       [0.7849557 , 0.2150443 ],
       [0.37899345, 0.62100655],
       [0.31683213, 0.68316787],
       [0.3009509 , 0.6990491 ],
       [0.25754083, 0.74245917],
       [0.55349928, 0.44650072],
       [0.52051622, 0.47948378],
       [0.72120075, 0.27879925],
       [0.14880137, 0.85119863],
       [0.22409477, 0.77590523],
       [0.85302259, 0.14697741],
       [0.91714155, 0.08285845],
       [0.09654353, 0.90345647],
       [0.3277294 , 0.6722706 ],
       [0.66009241, 0.33990759],
       [0.47609389, 0.52390611],
       [0.44001423, 0.55998577],
       [0.20887576, 0.79112424],
       [0.1783463 , 0.8216537 ],
       [0.45533557, 0.54466443],
       [0.6893534 , 0.3106466 ],
       [0.73863728, 0.26136272],
       [0.8399901 , 0.1600099 ],
       [0.19001459, 0.80998541],
       [0.54516654, 0.45483346],
       [0.77903962, 0.22096038],
       [0.65072406, 0.34927594],
       [0.78656024, 0.21343976],
       [0.88776978, 0.11223022],
       [0.25780614, 0.74219386],
       [0.69874615, 0.30125385],
       [0.3864439 , 0.6135561 ],
       [0.78656024, 0.21343976],
       [0.70306858, 0.29693142],
       [0.65072406, 0.34927594],
       [0.73284787, 0.26715213],
       [0.47609389, 0.52390611],
       [0.53930442, 0.46069558],
       [0.68979648, 0.31020352],
       [0.75414044, 0.24585956],
       [0.54254271, 0.45745729]])

In [45]:
predicted_proba.shape

(140, 2)

In [46]:
predicted_proba[:,1]

array([0.28778024, 0.41239991, 0.55662562, 0.22096038, 0.91541657,
       0.66896629, 0.70207504, 0.87043779, 0.21692179, 0.25291341,
       0.50485031, 0.77359703, 0.92969016, 0.26495948, 0.69466915,
       0.44964119, 0.44972574, 0.46069558, 0.59882226, 0.94679318,
       0.30125385, 0.22096038, 0.58365437, 0.58365437, 0.7587085 ,
       0.25682913, 0.48934806, 0.14296697, 0.80065765, 0.22096038,
       0.37028423, 0.68316787, 0.68825755, 0.52694241, 0.22096038,
       0.53492642, 0.22453007, 0.74389237, 0.40329273, 0.60301627,
       0.21343976, 0.45483346, 0.2403088 , 0.4388431 , 0.82622935,
       0.57857132, 0.69461059, 0.28778024, 0.22209028, 0.2061074 ,
       0.57577123, 0.36438663, 0.66896629, 0.27128561, 0.83334736,
       0.43399232, 0.88600663, 0.23396355, 0.37170685, 0.38209505,
       0.69796139, 0.65909803, 0.29392197, 0.79686146, 0.20956093,
       0.2699923 , 0.10399887, 0.22453007, 0.73944244, 0.30081832,
       0.22453007, 0.32688766, 0.90337554, 0.45745729, 0.59997247,
       0.22096038, 0.77863015, 0.72858977, 0.74344554, 0.67044828,
       0.24847708, 0.08983463, 0.23396355, 0.75440725, 0.4337004 ,
       0.12262459, 0.70691713, 0.58365437, 0.27413878, 0.68316787,
       0.17361794, 0.15261056, 0.22866894, 0.2699923 , 0.25291341,
       0.85119863, 0.29693142, 0.76416527, 0.24585956, 0.2150443 ,
       0.62100655, 0.68316787, 0.6990491 , 0.74245917, 0.44650072,
       0.47948378, 0.27879925, 0.85119863, 0.77590523, 0.14697741,
       0.08285845, 0.90345647, 0.6722706 , 0.33990759, 0.52390611,
       0.55998577, 0.79112424, 0.8216537 , 0.54466443, 0.3106466 ,
       0.26136272, 0.1600099 , 0.80998541, 0.45483346, 0.22096038,
       0.34927594, 0.21343976, 0.11223022, 0.74219386, 0.30125385,
       0.6135561 , 0.21343976, 0.29693142, 0.34927594, 0.26715213,
       0.52390611, 0.46069558, 0.31020352, 0.24585956, 0.45745729])

In [47]:
#Saving the model and Preparing it for Deployment
import pickle

In [48]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [49]:
with open('scalar', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)